"""phase 1 initial schema

Revision ID: 43c61153cc8c
Revises: 
Create Date: 2026-05-11 12:51:15.433692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c61153cc8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('dataset_source', sa.String(length=128), nullable=False),
    sa.Column('image_phase', sa.Enum('native', 'via', 'vili', 'green_filter', 'unknown', name='image_phase'), nullable=True),
    sa.Column('capture_device', sa.String(length=128), nullable=True),
    sa.Column('magnification_level', sa.Enum('low', 'medium', 'high', 'unknown', name='magnification_level'), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_dataset_source'), ['dataset_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_image_phase'), ['image_phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_sha256'), ['sha256'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('annotator', 'reviewer', 'admin', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('consensus_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.Enum('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', name='consensus_label'), nullable=False),
    sa.Column('derived_from', sa.JSON(), nullable=False),
    sa.Column('agreement_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('discarded_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('annotator_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discarded_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discarded_images_image_id'), ['image_id'], unique=False)

    op.create_table('image_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=False),
    sa.Column('annotator_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'reviewed', 'consensus', 'superseded', name='annotation_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('image_quality', sa.Enum('excellent', 'good', 'fair', 'poor', name='image_quality'), nullable=True),
    sa.Column('blur_present', sa.Boolean(), nullable=True),
    sa.Column('blood_present', sa.Boolean(), nullable=True),
    sa.Column('mucus_present', sa.Boolean(), nullable=True),
    sa.Column('specular_reflection_present', sa.Boolean(), nullable=True),
    sa.Column('lighting_issue', sa.Enum('none', 'under', 'over', 'uneven', name='lighting_issue'), nullable=True),
    sa.Column('usable_for_training', sa.Boolean(), nullable=True),
    sa.Column('scj_visibility', sa.Enum('fully_visible', 'partial', 'not_visible', name='scj_visibility'), nullable=True),
    sa.Column('transformation_zone_type', sa.Enum('TZ1', 'TZ2', 'TZ3', 'unknown', name='tz_type'), nullable=True),
    sa.Column('tz_visibility', sa.Enum('fully_visible', 'partial', 'not_visible', name='tz_visibility'), nullable=True),
    sa.Column('acetowhitening_severity', sa.Integer(), nullable=True),
    sa.Column('iodine_pattern', sa.Integer(), nullable=True),
    sa.Column('vascular_pattern', sa.Enum('normal', 'fine_punctation', 'coarse_punctation', 'fine_mosaic', 'coarse_mosaic', 'atypical', name='vascular_pattern'), nullable=True),
    sa.Column('color_tone', sa.Enum('pink', 'pale', 'dense_white', 'yellow', name='color_tone'), nullable=True),
    sa.Column('surface_contour', sa.Enum('smooth', 'micropapillary', 'nodular', 'ulcerated', name='surface_contour'), nullable=True),
    sa.Column('atypical_vessels_present', sa.Boolean(), nullable=True),
    sa.Column('colposcopic_impression', sa.Enum('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', name='diagnosis_label'), nullable=True),
    sa.Column('histopathology_result', sa.Enum('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', name='diagnosis_label_histo'), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'annotator_id', 'version', name='uq_annotation_version')
    )
    with op.batch_alter_table('image_annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotation_annotator_status', ['annotator_id', 'status'], unique=False)
        batch_op.create_index('ix_annotation_image_status', ['image_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_annotations_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_annotations_image_id'), ['image_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_annotation_id', sa.String(length=36), nullable=False),
    sa.Column('region_type', sa.Enum('bbox', 'polygon', 'mask', name='region_type'), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('lesion_label', sa.Enum('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', name='lesion_label'), nullable=True),
    sa.Column('lesion_location_clock', sa.Integer(), nullable=True),
    sa.Column('lesion_quadrant', sa.Enum('anterior', 'posterior', 'left_lateral', 'right_lateral', 'circumferential', name='lesion_quadrant'), nullable=True),
    sa.Column('lesion_size_percent', sa.Integer(), nullable=True),
    sa.Column('lesion_margins', sa.Enum('sharp', 'irregular', name='lesion_margins'), nullable=True),
    sa.Column('punctation_present', sa.Boolean(), nullable=True),
    sa.Column('punctation_severity', sa.Integer(), nullable=True),
    sa.Column('mosaic_present', sa.Boolean(), nullable=True),
    sa.Column('mosaic_severity', sa.Integer(), nullable=True),
    sa.Column('region_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_annotation_id'], ['image_annotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_image_annotation_id'), ['image_annotation_id'], unique=False)

    op.create_table('review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_annotation_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('approve', 'reject', 'edit', name='review_action'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_annotation_id'], ['image_annotations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_image_annotation_id'), ['image_annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_actions_reviewer_id'), ['reviewer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_actions_image_annotation_id'))

    op.drop_table('review_actions')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_image_annotation_id'))

    op.drop_table('regions')
    with op.batch_alter_table('image_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_annotations_image_id'))
        batch_op.drop_index(batch_op.f('ix_image_annotations_annotator_id'))
        batch_op.drop_index('ix_annotation_image_status')
        batch_op.drop_index('ix_annotation_annotator_status')

    op.drop_table('image_annotations')
    with op.batch_alter_table('discarded_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discarded_images_image_id'))

    op.drop_table('discarded_images')
    op.drop_table('consensus_labels')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_images_image_phase'))
        batch_op.drop_index(batch_op.f('ix_images_dataset_source'))

    op.drop_table('images')
    # ### end Alembic commands ###
