"""change colposcopic_impression to json array

Revision ID: b9383f714fc1
Revises: e4d5f6a7b8c9
Create Date: 2026-07-02 12:48:55.501614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9383f714fc1'
down_revision = 'e4d5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consensus_labels', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=postgresql.ENUM('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', 'INFLAMMATION', 'INFECTION', 'EROSION', name='consensus_label'),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='json_build_array(label::text)')

    with op.batch_alter_table('image_annotations', schema=None) as batch_op:
        batch_op.alter_column('colposcopic_impression',
               existing_type=postgresql.ENUM('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', 'INFLAMMATION', 'INFECTION', 'EROSION', name='diagnosis_label'),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='json_build_array(colposcopic_impression::text)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_annotations', schema=None) as batch_op:
        batch_op.alter_column('colposcopic_impression',
               existing_type=sa.JSON(),
               type_=postgresql.ENUM('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', 'INFLAMMATION', 'INFECTION', 'EROSION', name='diagnosis_label'),
               existing_nullable=True,
               postgresql_using="(colposcopic_impression->>0)::diagnosis_label")

    with op.batch_alter_table('consensus_labels', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.JSON(),
               type_=postgresql.ENUM('NORMAL', 'CIN1', 'CIN2', 'CIN3', 'AIS', 'INVASIVE_CANCER', 'INFLAMMATION', 'INFECTION', 'EROSION', name='consensus_label'),
               existing_nullable=False,
               postgresql_using="(label->>0)::consensus_label")

    # ### end Alembic commands ###
